### ISSUE TITLE
What version of ruby is it compatible with?

### ISSUE THREAD

**Issue by ghost** [dreverri/gollum-site#1]
First. Thanks for creating this. I was working with gollum and came across your fork. I gave it a spin on ruby 1.8.7-p302 and it gives following error

/Users/username/.rvm/gems/ruby-1.8.7-p302/gems/gollum-1.1.0/lib/gollum/page.rb:297:in `find_page_in_tree': undefined method`each' for #<Grit::Tree "d9f141202b9d9e222869f33456cdbd202152dc"> (NoMethodError)

**Comment by dreverri** [comment]
Thanks for pointing this issue out. I've updated gollum-site to work with gollum v1.1.0. The new version (v0.0.4) has been pushed to rubygems.
