### ISSUE TITLE
--watch not watching

### ISSUE THREAD

**Issue by abh** [dreverri/gollum-site#11]
I installed the directory_watcher gem, but --watch doesn't seem to do anything -- it just generates and exists (as without that option).  I tried with --debug_level debug; but even with that no errors or anything related to watching is mentioned.

```
$ gollum-site generate  --watch
Generated site in 0.659549(s)
```

**Comment by dreverri** [comment]
Watch is currently only defined to work with serve.

**Comment by abh** [comment]
Ah, that wasn't clear from the docs at all.   Consider this a documentation bug instead then!  :-)

**Comment by dreverri** [comment]
I've updated the README to address this issue.
