### ISSUE TITLE
xml syntax highlighting breaks liquid processing

### ISSUE THREAD

**Issue by stoicflame** [dreverri/gollum-site#15]
If you attempt syntax highlighting for xml, e.g.:

```xml
&lt;some example="xml/>
```

Then processing fails:

> Liquid error: Requires a Node, NodeSet or String argument, and cannot accept a NilClass. (You probably want to select a node from the Document with at() or search(), or create a new Node via Node.new().)

**Comment by tothda** [comment]
Try installing pygments.

**Comment by stoicflame** [comment]
> Try installing pygments.

Thanks for the tip!

**Comment by Zapotek** [comment]
I'm getting the same error on Heroku, is it possible to disable syntax highlighting in order to avoid this error?
