### ISSUE TITLE
"pretty" URL support

### ISSUE THREAD

**Issue by spilth** [dreverri/gollum-site#28]
For a page `foo.md` sitting in the root of my project, instead of having the URL `http://localhost:8000/foo.html` I would prefer `http://localhost:8000/foo/`

This would mean each page is actually generated as an index.html within the foo directory.

Any plans/desire to support this?

**Comment by grmrgecko** [comment]
I would like this as well. Shouldn't be hard.

**Comment by mpemer** [comment]
This would probably best be implemented by first not flattening the structure of the wiki, but rather generating the full folder structure. After this, one could simply add pages called index to the folders. spilth - how would you envision hosting your site after it has been generated? Would it live behind some web server that knows about index pages?

**Comment by spilth** [comment]
I've been putting my static sites on S3 which lets you set a default index page.

I currently do this using Jekyll which turns "foo.md" into "foo/index.html" and knows to just link to "/foo/".
