### ISSUE TITLE
Links don't use base_path

### ISSUE THREAD

**Issue by vladdu** [dreverri/gollum-site#3]
Hi! Very nice idea with gollum-site!

The generated internal links don't seem to use the provided base_path option, they still get prepended a "/". This might be ok if used with "gollum-site serve", but I want to use the results independently.

The links for css and images and javascript are ok.

**Comment by dreverri** [comment]
Hi Vladdu,

Sorry for not getting back to you sooner. I'm not able to reproduce this issue. What version of gollum-site are you using? What is the base_path you are trying to set?

Thanks,
Dan

**Comment by vladdu** [comment]
Hi!
I was using version 0.0.6.
The problem is that css and image links are generated with "$base_path" and page links with "$base_path/", meaning that to get relative paths one has to use base_path "./", which is not obvious.
/Vlad

**Comment by dreverri** [comment]
The best solution for this issue is the one mentioned; use "./" for relative paths.
