### ISSUE TITLE
Can't install to ~/.gem

### ISSUE THREAD

**Issue by beerriot** [dreverri/gollum-site#5]
gollum-site demands to be installed in /usr/bin.  I'm a ruby/gem n00b, but the other gems seem to install in ~/.gem if they don't have permissions to /usr/bin.  Is it possible to do the same for gollum-site?

```
$ gem install gollum-site
Fetching: gollum-site-0.1.7.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /usr/bin directory.
```

**Comment by dreverri** [comment]
The location that rubygems installs binaries to is governed by an individuals environment.

I believe rubygems will install binaries to the same location as your ruby binary. I've found it much easier to manage gems when using RVM (http://rvm.beginrescueend.com/). This allows users to setup isolated rubies/gems.

It looks like you can also specify the location of the bindir for your rubygems in the ~/.gemrc file using the "--bindir" option:
http://stackoverflow.com/questions/333508/can-gem-install-be-configured-to-install-executables-outside-usr-bin-by-defau
